### ISSUE TITLE
お掃除しないので caller がずっと残る

### ISSUE THREAD

**Issue by FujiHaruka** [realglobe-Inc/sugo-hub#28]
実証実験後にサーバーを覗いてみました。

UI用の sugo-hub の `/callers` を見ると、 800 個ほどの callers がいることになっていました。
その正体はおそらくブラウザで生成された caller がブラウザを閉じると終処理をせずに消滅するので、ブラウザでシステムにアクセスするたびに増えていったのだと思います。

actor 側で caller にデータを送るたびに 800 個ほどの caller （大半は消えている）を find しようとするので、ゴミ屑callerがたまるとパフォーマンス低下が懸念されます。

原因は、caller 側で `DISCONNECT` イベントは走るが `LEAVE` イベントが走らない時に、うまく終処理ができないといった感じでしょうか。

**Comment by okunishinishi** [comment]
done
